DROP TABLE IF EXISTS TEACHERS;

CREATE TABLE TEACHERS (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  number_id VARCHAR(8) NOT NULL UNIQUE,
  NAME VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  phone VARCHAR(250)
);
DROP TABLE IF EXISTS STUDENTS;

CREATE TABLE STUDENTS (
  id BIGINT AUTO_INCREMENT  PRIMARY KEY,
  number_id VARCHAR(8) NOT NULL UNIQUE,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) NOT NULL,
  phone VARCHAR(250),
  teacher BIGINT
);
